version: '3.8'

networks:
  kdancn:
    external: true

services:
  server:
    build: .
    image: php_compdf_server
    container_name: php_compdf_server
    networks:
      - kdancn
    tty: true
    #restart: always
    # ports:
    #   - "3020:3020"
    volumes:
      - .:/php_compdf_server
      # 第一次build up时注释掉这行，容器跑起来后，拷贝容器内vendor目录到主机
      # docker cp $(docker inspect -f '{{.Id}}' php_compdf_server):/php_compdf_server/vendor /var/www/php_compdf_server
      - ./.env:/php_compdf_server/.env
      - ./storage/logs:/php_compdf_server/storage/logs
      - ./public:/php_compdf_server/public
